[feature] API namespace associations
## API Namespace Association Feature

### Introduction

The API Namespace Association feature allows you to define associations between different API namespaces in your application. It enables you to establish relationships such as has_one, has_many, and belongs_to between API namespaces. This feature enhances the flexibility and convenience of working with API resources by automatically generating dynamic methods for accessing associated resources.

### Usage
Associations can be defined while creating or editing API namespaces

https://github.com/restarone/violet_rails/assets/50227291/4e0a6736-846c-4ac1-88bb-165db5e0df98

OR using rails console

`ApiNamespace.friendly.find('shops').update(associations: [{type: 'has_many', namespace: 'products'}])`

NOTE: Associated namespace (products) must exist before creating an association.

### Foreign Key Properties
After assigning associations between API namespaces, the associated API namespace will automatically have a foreign key property added to its definition.

For example, if you have a belongs_to association between the product API namespace and the shop API namespace, the product resources will have a `shop_id` property added to them. This property represents the foreign key relationship to the associated shop resource.

### Corresponding Associations
Corresponding associations are generated 

When defining an association between two API namespaces, the corresponding association is automatically set up in the associated namespace.

- For `has_one` association: The associated namespace will have a `belongs_to` association with the original namespace.

- For `belongs_to` association: The associated namespace will have a `has_many` association with the original namespace, if an association between them is already not defined in associated namespace.

- For `has_many` association: The associated namespace will have a `belongs_to` association with the original namespace.

This ensures that the associations between the API namespaces are properly set up, allowing you to access the associated resources conveniently.

### Dependent option
You can specify the following association dependent options for each association:

blank: if set to `blank`, the associated resources will be left as it is when the parent resource is destroyed

destroy: If set to `destroy`, all the associated resources will be destroyed along with the parent resource

restrict_with_error: If set to `restrict_with_error`, the parent resource cannot be deleted if it has associated resources. An error will be added to the parent resource.

https://github.com/restarone/violet_rails/assets/50227291/39a33377-dfd2-42d8-ad77-2c820c613eeb


### Dynamic Methods
Once you have defined the associations between API namespaces, the API resources within these namespaces will automatically have dynamic methods generated based on the association type. These methods provide easy access to associated resources.

For each association type, the following dynamic methods are available:

#### `has_many` Association:
If a `shops` API namespace has a `has_many` association with a `products` API namespace, the dynamic method generated would be:

```
shop = ApiNamespace.friendly.find('shops').api_resources.first
shop.products
```

#### `has_one` Association:
If a `shops` API namespace has a `has_one` association with a `users` API namespace, the dynamic method generated would be:

```
shop = ApiNamespace.friendly.find('shops').api_resources.first
shop.user
```

#### `belongs_to` Association:
If a `products` API namespace has a `belongs_to` association with a `shops` API namespace, the dynamic method generated would be:

```
product = ApiNamespace.friendly.find('products').api_resources.first
product.shop
```

https://github.com/restarone/violet_rails/assets/50227291/47b12a92-a45b-4a75-8155-fb721010f076


DEMO:

https://github.com/restarone/violet_rails/assets/50227291/54cbb05f-84af-4ae7-9d29-1b16dab78567